### ISSUE TITLE
Set token to never expire

### ISSUE THREAD

**Issue by sotoole** [jonathan-dejong/simple-jwt-authentication#10]
Is it possible to set the token to never expire? I imagine it's done through 'jwt_auth_expire'. I've tried 0 and null as the expiration times but neither work.

**Comment by jonathan-dejong** [comment]
Hi @sotoole 

you can just set it ridiculously high :)

**Comment by sotoole** [comment]
OK but when my token expires in the year 6000 and all my users are logged out, I'm blaming you!

**Comment by jonathan-dejong** [comment]
I recommend setting a notice in your calendar to extend the date #offthehook
