### ISSUE TITLE
Just a comment, now testing

### ISSUE THREAD

**Issue by tkserver** [jonathan-dejong/simple-jwt-authentication#11]
Hi Jonathan.

I have new project I'm working on for a WP/bbPress ios/android app.  This isn't an "issue" but just a comment that I'm successfully using your plugin in my local environment already.  I plan to participate and post any real issues or suggestions as they come up!

Thanks for taking this project on.

**Comment by jonathan-dejong** [comment]
Hi @tkserver 

Glad to hear and I welcome all feedback :)
