### ISSUE TITLE
Documentation request

### ISSUE THREAD

**Issue by flymikeG** [jonathan-dejong/simple-jwt-authentication#15]
Please, _please_ expand that part of the documentation beginning "Eable PHP HTTP Authorization Header".
Specifically:

1. Shared Hosts: "Most of the shared hosts have disabled the HTTP Authorization Header": I run my own host. I wonder if I have (inadvertently) disabled it. Where do I look? Do you mean the http server (Apache)? If so, what configuration value should I look for? And how does that RewriteRule change Apache configuration? Or is that a workaround?
2. WPEngine: "To enable this option...". Which option? Is this still the Shared Hosts issue?

Is it this particular plugin which has a dependency on these htaccess changes?

**Comment by jonathan-dejong** [comment]
Hi @flymikeG 

I've only copied this section from the plugin this plugin is based on:
https://github.com/Tmeister/wp-api-jwt-auth

I myself do not have any sites running on WPEngine so really.. I have no "inside" information to give. 
I've had to set 
`
RewriteEngine on
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]
`
On some of my shared host projects.. Thus done in the .htaccess file directly. 

I can't answer for you if you've disabled the HTTP Authorization Header but I suppose it's possible. 
If you want you can also explicitly set it in your httpd.conf file and then restart apache. 

> WPEngine: "To enable this option...". Which option? Is this still the Shared Hosts issue?
The option of allowing HTTP_AUTHORIZATION.
So you would either use the rewriteEngine code OR the WPEngine code. 

Hope that clears some up for you :)
