### ISSUE TITLE
Set token length in WP back end

### ISSUE THREAD

**Issue by tkserver** [jonathan-dejong/simple-jwt-authentication#16]
I'm going to change the token length for a client and it would be nice for us to be able to just set the length in the WP back end instead of hard coding it.

**Comment by jonathan-dejong** [comment]
To what end would you need to change the token length?

**Comment by tkserver** [comment]
I want my token length 6 months, but my client on another project wants it to be 2 months. I think it is 1-2 weeks right now?

**Comment by sotoole** [comment]
@tkserver Try adding this is to your functions.php file:

```
function  extend_jwt_auth_expire() {
    return time() + (DAY_IN_SECONDS * 182); //182 days is roughly 6 months
}
add_filter( 'jwt_auth_expire', 'extend_jwt_auth_expire' );
```

**Comment by sotoole** [comment]
@tkserver Nevermind, just realized you were asking about adding a setting in the admin.

**Comment by jonathan-dejong** [comment]
I don't think it's a setting that should be added to an admin setting as 99% of people probably wont want to change it. But you can always use the filter @sotoole published above :)
