### ISSUE TITLE
Revoke Tokens Not Working Subdirectory

### ISSUE THREAD

**Issue by tribalboy3000** [jonathan-dejong/simple-jwt-authentication#2]
Hello, not sure if I'm doing something wrong but when I click Revoke or Remove all expire tokens I get a page not found error:

Remove all expired tokens url:
https://mysite.com/**dev**/**dev**/wp-admin/profile.php?wp_http_referer=%2Fdev%2Fwp-admin%2Fusers.php&remove_expired_tokens=1

Revoke:
https://mysite.com/**dev**/**dev**/wp-admin/profile.php?wp_http_referer=%2Fdev%2Fwp-admin%2Fusers.php&revoke_token=0d53a97d-5d19-46cf-870f-382e0ddf75f0

The buttons seem to add an extra dev directory.

**Comment by tribalboy3000** [comment]
Is there a work around for this until its figured out? I tried the url without the extra dev but that didn't work and I have a ton of tokens taking up my screen

**Comment by jonathan-dejong** [comment]
Hi @tribalboy3000 

Are you just using ** for emphasis or actually have that in your dev urls? :D 
The button uses site_url(). 
What url do you get if you use site_url() yourself somewhere? Is this in a network?

**Comment by jonathan-dejong** [comment]
Hello,

Just wanted to say that this is fixed with v 1.1
https://github.com/jonathan-dejong/simple-jwt-authentication/releases/tag/v.1.1
