### ISSUE TITLE
rest_user_invalid_id

### ISSUE THREAD

**Issue by olivermpo** [jonathan-dejong/simple-jwt-authentication#20]
Hi

I'm trying to authenticate using the simple-jwt-authentication, and I am able to get a token response, but the moment I try to do anything on the API endpoints I get back for example trying to do create a post:
{
    "code": "rest_cannot_create",
    "message": "Sorry, you are not allowed to create posts as this user.",
    "data": {
        "status": 401
    }
}

If I try to  identify what user it is authenticated using (/wp-json/wp/v2/users/me)
{
    "code": "rest_user_invalid_id",
    "message": "Invalid user ID.",
    "data": {
        "status": 404
    }
}

I would appreciate any help with this!

Regards

Oliver

P.s.

Here is a sample  php cUrl

<?php

$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => "http://domainname/wp-json/wp/v2/posts",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 30,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "POST",
  CURLOPT_POSTFIELDS => "{\r\n\t\"title\" : \"Blah\",\r\n\t\"status\": \"publish\",\r\n\t\"content\": \"Blah Blah\"\r\n}\r\n",
  CURLOPT_HTTPHEADER => array(
    "authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1dWlkIjoiNjE2MzJlNmYtYjk2MC00ZGJkLWE5OTAtMGJhMTkxNGQ5MWQ0IiwiaXNzIjoiaHR0cDpcL1wvdG9kb3NvYnJlbG9zcHVtYXMuaW5mbyIsImlhdCI6MTUxOTkxMDU3NCwibmJmIjoxNTE5OTEwNTc0LCJleHAiOjE1MjA1MTUzNzQsImRhdGEiOnsidXNlciI6eyJpZCI6IjIifX19.jnPg_BTuje3gou-rvnEa5xVCRfK__hgJGJ8UYC1i0VU",
    "content-type: application/json"
  ),
));

$response = curl_exec($curl);
$err = curl_error($curl);

curl_close($curl);

if ($err) {
  echo "cURL Error #:" . $err;
} else {
  echo $response;
}

**Comment by jonathan-dejong** [comment]
Hi,

Have you tried adding the htaccess rules?
https://github.com/jonathan-dejong/simple-jwt-authentication/wiki/Documentation#shared-hosts
