### ISSUE TITLE
Strange error on authentication.

### ISSUE THREAD

**Issue by harlet** [jonathan-dejong/simple-jwt-authentication#21]
Hi there!

If I access the Url (GET) `/wp-json/simple-jwt-authentication/v1/token` on a WPEngine live site; I get:
```
{
  "code": "jwt_auth_bad_auth_header",
  "message": "Authorization header malformed.",
  "data": {
    "status": 403
  }
}
```

I say is strange because searching thru the plugin's code I found that, the error is returned in a `validate_token` function.

Even if a do a POST request, I have the same error.

**Comment by jonathan-dejong** [comment]
Hi @harlet 

Have you checked out the wiki about WPengine?
`SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1`

https://github.com/jonathan-dejong/simple-jwt-authentication/wiki/Documentation#wpengine

**Comment by harlet** [comment]
Already had that setup.
The problem was the cross-origin.

Thank you!
