### ISSUE TITLE
Remove HTML from error messages

### ISSUE THREAD

**Issue by tkserver** [jonathan-dejong/simple-jwt-authentication#24]
I'm working on a native app.  When I receive a 403 login error, the response looks like this:

`<strong>ERROR</strong>: The password field is empty.`

The strong HTML tag (and other HTML) does not work natively.  I suggest removing the word "error" since we already know it is an error, and removing any HTML tags so the error response is plain text.

**Comment by jonathan-dejong** [comment]
Hey,

The response output is actually the native response from WordPress (which is what's returned by WordPress REST). Honestly I don't really feel like making custom messages for each situation and mapping them to WPs :/ 
Maybe look into if you can filter WordPress core messages directly in your installation instead?

**Comment by tkserver** [comment]
Thanks Jonathan. I know some of the WP dev team. Perhaps I can mention this.

**Comment by jonathan-dejong** [comment]
Yeah it might be optimal if the REST actually dont return any formatted HTML :)
