### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by ens-ap5** [jonathan-dejong/simple-jwt-authentication#25]
Hi Jonathan, I'm trying to use your plugin to access a published post with status 'private', so that I can test fetching the content without making said post public. I have been able to fetch a public post using the WP REST API, so I know that part of my code is OK.

I've followed all the configuration settings, and can retrieve and validate my token. However it's not clear to me how to access standard WP REST endpoints using the authentication token, as the only examples provided in the documentation use your own 'token/validate' endpoint. 

For example, I'm trying to access the endpoint '/wp-json/wp/v2/posts?tags=43', which should return the private post, but my REST code is returning a status of '403: Forbidden'. My understanding is that the plugin should be intercepting this request and authorizing it, but maybe I'm missing something?

**Comment by jonathan-dejong** [comment]
Hi Anne Lyle, 

Read the Usage section of the documentation :) 
https://github.com/jonathan-dejong/simple-jwt-authentication/wiki/Documentation#usage

Basically you need to store the token received through the token endpoint and send that with each request to the WP REST API as an authorization header.
`'authorization': 'Bearer ' + token`

Best of luck with your project!

**Comment by ens-ap5** [comment]
I read the documentation, thanks, and have checked that the 'Authorization' header is getting passed into the HTTP request, but it's being ignored by WordPress. I'll check with my web host to see if they're blocking authorisation somehow despite me enabling it in .htaccess.

**Comment by jonathan-dejong** [comment]
Ah yeah then the issue is likely the host.
Have you tried both here: https://github.com/jonathan-dejong/simple-jwt-authentication/wiki/Documentation#eable-php-http-authorization-header

**Comment by ens-ap5** [comment]
Yes. I've raised a ticket with our hosting company, but I'm currently working on other more urgent things :)
