### ISSUE TITLE
Use a encrypted password with the wp_get_current_user function

### ISSUE THREAD

**Issue by ArraysNL** [jonathan-dejong/simple-jwt-authentication#26]
Hi,

Thanks for the plugin. And I hope you can help me with our problem.

We using the plugin now on a development version. And like to use it on a production version. Therefore we like to create a JWT token per user.

We using PHP and Javascript, below is the code.

```
wp_localize_script( 'jwt', 'username', 'test' );
wp_localize_script( 'jwt', 'password', 'test' );
```

```
const set_token = axios( {
                method: 'post',
                url: 'https://url.local/wp-json/simple-jwt-authentication/v1/token',
                data: {
                    username: username,
                    password: password
                }
            } ).then( function( response ) {
                console.log( response );
            } )
            .catch( function( error ) {
                console.log( error );
            } );
```

Now we like to user the wp_get_current_user function, is this possible? Because using the following code won’t work. Or are we going in the wrong direction?

```
$current_user = wp_get_current_user();

wp_localize_script( 'jwt', 'username', $current_user->data->user_login );
wp_localize_script( 'jwt', 'password', $current_user->data->user_pass );
```

**Comment by jonathan-dejong** [comment]
Hi @ArraysNL 

So what you're trying to achieve is to have the user automatically authorized?
I'm not sure if that is possible. You're using the user_pass value from current_user but I'm pretty sure that is the hashed value of their password. Not the actual password. 

You're also using wp_localize_script incorrectly. Read up on it here: https://developer.wordpress.org/reference/functions/wp_localize_script/

So for this to have any chance of working you'd have to first use that correctly.. and then find a way to reverse engineer the hashed password by using the unique keys in wp-config.php.

But from what I can tell you're trying to authenticate the user with JWT from inside the wordpress installation when they are already logged in? I don't understand why you'd need to do that as they are already logged in and thus authenticated.

**Comment by ArraysNL** [comment]
Thanks for the reply.

The users are logged in with a SSO provider. So they are already logged in on the website. But on the website we want to create a JWT token, so we can send it to a external API where the token can be verified.

So the problem is that we indeed need a token for a already logged in user. Don't know if there is a solution for this indeed.

Thanks for the wp_localize_script info, will take a look to this don't want to use things the wrong way.

**Comment by jonathan-dejong** [comment]
Does the SSO not support the REST API too? I figure you might be able to just use the stored auth token from the SSO instead? Honestly I have little experience with SSOs in that way. 

Otherwise the only option I can think of is to have the user submit a form with their username/password in order to retrieve a token from JWT and store it for later use. You can set the token to live a very very long time. However I get that it wont work if the user don't actually know their password.. 

Maybe you should look at a different auth approach? 
Like application password: https://wordpress.org/plugins/application-passwords/
