### ISSUE TITLE
simple-jwt-authentication rewrite my Custom post-type and field name (PODS)

### ISSUE THREAD

**Issue by chrisgate** [jonathan-dejong/simple-jwt-authentication#28]
hi @jonathan-dejong I used PODS to create cool custom types and all that but as soon as upload and activate our awesome authentication plugin all Pods custom name changed
e.g:
 pods name : chris_gate      then change to pod name: chris-gate
meaning all names with underscore( _ ) change to hyphen ( - ). 

Below are the url to snapshot for the change image, hosted on https://imgbb.com/
https://ibb.co/ct3zro
https://ibb.co/j4OccT
https://ibb.co/m2jHcT

Thanks in anticipations.

Chris

**Comment by jonathan-dejong** [comment]
Hey Chris,

Hmmm odd. 
I cant think of anything in this plugin that would even remotely interfere with PODS in that way.. 

It's possible it's a bug in pods tho. I found an older issue regarding the same thing:
https://github.com/pods-framework/pods/issues/3499

I'm gonna assume you've updated your pods plugin since then :D

**Comment by chrisgate** [comment]
I used https://github.com/Tmeister/wp-api-jwt-auth now with fresh installation and nothing changed

But i am confused now that you pointed me to that issue and i am using the latest version of pods

Now install Tmeister and i dont the error got me thinking.

Truth is i need urs bcoz it meet my needs.

I have recreate and delete many time with every plugin i have before i notice this..

Thanks for ur time.

**Comment by chrisgate** [comment]
if u could install pods and simple-jwt-authentication

then create table based pod type and see what will happen...

Thanks

**Comment by chrisgate** [comment]
@jonathan-dejong I am ver very sorry.............its my plugin that breaks it.
I guess i over trust my plugin...............i guess i am having trust issue ...lol

here is the code that breaks it:
```
**add_filter( 'pods_api_pre_save_pod_item', 'slug_set_title', 10, 2);
function slug_set_title($pieces, $is_new_item) {
	//check if is new item, if not return $pieces without making any changes
	if ( ! $is_new_item ) {
		return $pieces;
	}
	//make sure that all three fields are active
	$fields = array( 'post_title', 'attendee_name', 'event_name','participation_type_name','ticket_type_name' );
	foreach( $fields as $field ) {
		if ( ! isset( $pieces[ 'fields_active' ][ $field ] ) ) {
			array_push ($pieces[ 'fields_active' ], $field );
		}
	}
	//set variables for fields empty first for saftey's sake
	$attendee_name = $event_name = $participation_type_name = $ticket_type_name = '';
	//get value of "sandwich" if possible
	if ( isset( $pieces[ 'fields' ][ 'attendee_name' ] ) && isset( $pieces[ 'fields'][ 'attendee_name' ][ 'value' ] ) && is_string( $pieces[ 'fields' ][ 'attendee_name' ][ 'value' ] ) ) {
        $attendee_name = $pieces[ 'fields' ][ 'attendee_name' ][ 'value' ];
        //set post title using $sandwich and $beverage
	    $pieces[ 'object_fields' ][ 'post_title' ][ 'value' ] =  $attendee_name;
	}
	//get value of "beverage" if possible
	if ( isset( $pieces[ 'fields' ][ 'event_name' ] ) && isset( $pieces[ 'fields'][ 'event_name' ][ 'value' ] ) && is_string( $pieces[ 'fields' ][ 'event_name' ][ 'value' ] ) ) {
        $event_name = $pieces[ 'fields' ][ 'event_name' ][ 'value' ];
        //set post title using $sandwich and $beverage
	    $pieces[ 'object_fields' ][ 'post_title' ][ 'value' ] =  $event_name;
    }
    //get value of "sandwich" if possible
	if ( isset( $pieces[ 'fields' ][ 'participation_type_name' ] ) && isset( $pieces[ 'fields'][ 'participation_type_name' ][ 'value' ] ) && is_string( $pieces[ 'fields' ][ 'participation_type_name' ][ 'value' ] ) ) {
        $participation_type_name = $pieces[ 'fields' ][ 'participation_type_name' ][ 'value' ];
        //set post title using $sandwich and $beverage
	    $pieces[ 'object_fields' ][ 'post_title' ][ 'value' ] =  $participation_type_name;
	}
	//get value of "beverage" if possible
	if ( isset( $pieces[ 'fields' ][ 'ticket_type_name' ] ) && isset( $pieces[ 'fields'][ 'ticket_type_name' ][ 'value' ] ) && is_string( $pieces[ 'fields' ][ 'ticket_type_name' ][ 'value' ] ) ) {
        $ticket_type_name = $pieces[ 'fields' ][ 'ticket_type_name' ][ 'value' ];
        //set post title using $sandwich and $beverage
	    $pieces[ 'object_fields' ][ 'post_title' ][ 'value' ] = $ticket_type_name;
	}
	// //set post title using $sandwich and $beverage
	// $pieces[ 'object_fields' ][ 'post_title' ][ 'value' ] = $sandwich . ' and ' . $beverage;
	//return $pieces to save
	return $pieces;
}
function easy_update_slug( $data, $postarr ) {
    if ( ! in_array( $data['post_status'], array( 'draft', 'pending', 'auto-draft','published' ) ) ) {
        $data['post_name'] = sanitize_title( $data['post_title'] );
    }

    return $data;
}
add_filter( 'wp_insert_post_data', 'easy_update_slug', 99, 2 );**
```

I still dont know what i did wrong here

**Comment by jonathan-dejong** [comment]
Hi!

Its the `sanitize_title()` function :) 

It converts _ to - 
https://codex.wordpress.org/Function_Reference/sanitize_title

**Comment by jonathan-dejong** [comment]
I think you could use pods own clean function:

https://github.com/pods-framework/pods/blob/1397549aa7833864c1c43ddfc16725feeda302e7/classes/PodsForm.php#L1112

`PodsForm::clean( $data['post_title'] )`

**Comment by chrisgate** [comment]
@jonathan-dejong thanks........... i think anything clean or sanitize_title give the same issues..
but i have rewrite my code and everything should be fine now.

Thanks again

**Comment by jonathan-dejong** [comment]
The clean function is what pods use themselves and its supposed to allow for underscores so you should be able to use that just fine :) 

At least unless they've changed it again. 

But anyway, best of luck with your project!

**Comment by chrisgate** [comment]
@jonathan-dejong thank for the luck u wish me.

Please how do return "role" as part return values when i go to this end point                                 
   /simple-jwt-authentication/v1/token

and which class should add more code.

Thanks in anticipations.

Cheers

**Comment by jonathan-dejong** [comment]
Short answer: you dont. 
Instead request the wordpress endpount for retrieving user data. refer to the rest api docs for how 😉

**Comment by chrisgate** [comment]
@jonathan-dejong Thanks
