### ISSUE TITLE
Process for creating new user?

### ISSUE THREAD

**Issue by tjb1187** [jonathan-dejong/simple-jwt-authentication#29]
Hi your plugin looks great. My only question for now is how do you create new users? Can visitors make a new user account from the front end? Thanks

**Comment by jonathan-dejong** [comment]
Hi,

Thanks!
This plugin only handles authentication. It does not actually create/update/delete anything :)
You're gonna wanna have a look at the official rest handbook:
https://developer.wordpress.org/rest-api/reference/users/

**Comment by chrisgate** [comment]
@jonathan-dejong  you love to refer us to Wordpress Docs.

@tjb1187 u can try this plugin out.................  https://github.com/SK8-PTY-LTD/wp-rest-user

**Comment by jonathan-dejong** [comment]
It has a lot of stuff! :) 
And these questions are not related to the plugin I provide as open source. 
I just try to help out as much as time lets me with work and family on top of open source contributions ;)

**Comment by chrisgate** [comment]
U know in wordpresss u have to login as admin to register..............that mean admin will always be needed but that plugin above resolved it.
It wil be nice if u could implement that or have small plugin it for it....just bcoz we love ur work.

**Comment by chrisgate** [comment]
in wordpress @jonathan-dejong u are one of my mentor ....i love the clear work u have done..........i am c# developer .

**Comment by jonathan-dejong** [comment]
Thank you Chris that's very kind of you :) 

The plugin you linked seem to do what OP wants tho so there's not really a need for me to create another one. Thanks for sharing!
