### ISSUE TITLE
Don't expose SIMPLE_JWT_AUTHENTICATION_SECRET_KEY

### ISSUE THREAD

**Issue by kasparsd** [jonathan-dejong/simple-jwt-authentication#31]
Per [docs](https://github.com/jonathan-dejong/simple-jwt-authentication/wiki/Documentation#configure-the-secret-key):

> This secret key must be unique and never revealed.

Per [Use JWT The Right Way](https://stormpath.com/blog/jwt-the-right-way):

> The secret signing key should only be accessible by the issuer and the consumer; it should not be accessible outside of these two parties.

However, currently the secret is revealed in the plugin settings to all users with the `manage_options` capability. Could we make this field write only so that users who don't want to set the `SIMPLE_JWT_AUTHENTICATION_SECRET_KEY` constant can still add the key but never see it?

**Comment by jonathan-dejong** [comment]
Hi @kasparsd 

Good point!
It should be changed to an input type password field :) 

I'll look into it as soon as I can find the time. Or if you prefer to make a PR that is more than welcome!

**Comment by jonathan-dejong** [comment]
Coming in 1.4 soon!
