### ISSUE TITLE
rest_cannot_create 401

### ISSUE THREAD

**Issue by jeanrinvil** [jonathan-dejong/simple-jwt-authentication#33]
Hi,

I'm triying to use your plugin to auth with wp rest api, but when I hit /wp/v2/posts for example with the token in bearer auth via postman, I always have 401 error rest_cannot_create

What I do wrong ? 

Thanks

**Comment by isuke01** [comment]
Check your .htaccess if it is correctly set, or other plugin issue, also wp-config consts `SIMPLE_JWT_AUTHENTICATION_SECRET_KEY` I had same issue, WP replace my .htaccess edits, just dont put it inside `# BEGIN WordPress # END WordPress`
