### ISSUE TITLE
Dont use WP_DIE in rest return

### ISSUE THREAD

**Issue by isuke01** [jonathan-dejong/simple-jwt-authentication#38]
File `class-simple-jwt-authentication-rest.php`
**Line 501**  Please dont use wp_die(...) function, it could break whole output in application.
Just maybe return it as another error like `jwt_auth_reset_password_not_allowed` with same message as wp_die() called?

**Comment by jonathan-dejong** [comment]
Hi @isuke01 

Thanks for the feedback!
