### ISSUE TITLE
Endpoint - New User Confirmation Email

### ISSUE THREAD

**Issue by alexjuniodev** [jonathan-dejong/simple-jwt-authentication#44]
Is there an endpoint for sending a confirmation email?

**Comment by jonathan-dejong** [comment]
Hi @alexjuniodev 

No there's not. This plugin is really only made to authenticate users right now.
Not as a full-fledged user handling REST plugin :)

However I would imagine that if you create a user with WP REST API it'll send the standard confirmation email:
https://developer.wordpress.org/rest-api/reference/users/#create-a-user
