### ISSUE TITLE
add $user param to the 'jwt_auth_expire' filter

### ISSUE THREAD

**Issue by gordielachance** [jonathan-dejong/simple-jwt-authentication#48]
Hi!
I would like to have a different expiry time depending of the user.
Would it be possible to change 

    $expire = apply_filters( 'jwt_auth_expire', $issued_at + (DAY_IN_SECONDS * 7), $issued_at );

to

    $expire = apply_filters( 'jwt_auth_expire', $issued_at + (DAY_IN_SECONDS * 7), $issued_at, $user->data->ID );

?

**Comment by gordielachance** [comment]
https://github.com/jonathan-dejong/simple-jwt-authentication/pull/50

**Comment by jonathan-dejong** [comment]
Adding the entire $user variable as a parameter to this filter 👍
