### ISSUE TITLE
revoke token buttons are not working

### ISSUE THREAD

**Issue by gordielachance** [jonathan-dejong/simple-jwt-authentication#49]
revoke token buttons are not working in the backend profile of users.

**Comment by gordielachance** [comment]
I found the issue.
https://github.com/jonathan-dejong/simple-jwt-authentication/pull/50

**Comment by jonathan-dejong** [comment]
1.4.0 out: https://github.com/jonathan-dejong/simple-jwt-authentication/releases/tag/1.4.0
