### ISSUE TITLE
Working Together

### ISSUE THREAD

**Issue by tkserver** [jonathan-dejong/simple-jwt-authentication#5]
Hi Jonathan.  I'm using the original plugin for authentication to a bbPress forum, and it is working great.  I'm going to move to your version as I have had to make my own api for the simplest things like getting the logged in user's ID!

I would like to help support this plugin like I have helped support the bbPress api with testing and suggestions.  Do you have a slack?

First question/suggestion, registration via API.  Does it exist?

**Comment by jonathan-dejong** [comment]
Hi @tkserver 

Thank you. Of course I welcome all kinds of help. 
I do not have a slack specific for this plugin as it's "just" another open source plugin I try to improve for free :) However the issues here on github is probably a good enough starting point for all kinds of conversation about the plugin. 
I'll also gladly welcome any PRs after testing them out. 

There is currently no way to register via this plugin and I don't think it's needed. Look at the Core functionality:
https://developer.wordpress.org/rest-api/reference/users/#create-a-user

**Comment by tkserver** [comment]
Hmm. Ok. How about password reset and such?  I didn't see that in the WP api.

**Comment by tkserver** [comment]
I've looked into the WP API create a user link you mentioned. Creating a user can only be done via API if logged in, so it's an admin function, not a registration function.  After an hour or so of looking all over the web it would seem that WP does not have a registration option in their API, which is intentional.

**Comment by jonathan-dejong** [comment]
Yes there's an endpoint for requesting a new password :) It's in the documentation here on github!

Ah I see, why is that? Security issues?
