### ISSUE TITLE
CORS OPTION Preflight fails

### ISSUE THREAD

**Issue by sempostma** [jonathan-dejong/simple-jwt-authentication#54]
`Access to fetch at '/simple-jwt-authentication/v1/token' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

**Comment by jonathan-dejong** [comment]
https://github.com/jonathan-dejong/simple-jwt-authentication/wiki/Documentation#configurate-cors-support

**Comment by sempostma** [comment]
This is with cors support enabled of course.

**Comment by sempostma** [comment]
> https://github.com/jonathan-dejong/simple-jwt-authentication/wiki/Documentation#configurate-cors-support

The problem is that the CORS support option is not working.

**Comment by jonathan-dejong** [comment]
Have you also had a look at these:
https://github.com/jonathan-dejong/simple-jwt-authentication/wiki/Documentation#eable-php-http-authorization-header

What host are you using?
