### ISSUE TITLE
Add user with API

### ISSUE THREAD

**Issue by cubeur** [jonathan-dejong/simple-jwt-authentication#56]
First... thanks for your plugin  :)
Is there a possibility that in a future version you'll add a new end-point to add User please ?

**Comment by jonathan-dejong** [comment]
Hi @cubeur 
There's no need for that. 
WP already have an endpoint for manipulating users:
https://developer.wordpress.org/rest-api/reference/users/

best of luck!

**Comment by cubeur** [comment]
Thanks for your reply, in fact i think it "could" be useful to have this endpoint like this plugin
https://wordpress.org/plugins/wp-rest-user/
because with WP rest api it is not possible to create users without admin credentials.. and in my app (for exemple) i would like to create users from the app and then admin user with your plugin, without put the admin login/pwd in the app  ;)

thanks for your time, have a nice day

**Comment by jonathan-dejong** [comment]
I see! 
I think this is out of scope for this plugin but I understand the usability of it. Looks like you found another plugin that does this however.
It's also really easy to add your own endpoint to handle user registration (I'm actually doing exactly that in a current project).

**Comment by cubeur** [comment]
:)   so i'll try to code in PHP.  thanks again.
