### ISSUE TITLE
Documentation / refresh token

### ISSUE THREAD

**Issue by alexbonhomme** [jonathan-dejong/simple-jwt-authentication#58]
Hey!

First, thanks for you work :-)

I was looking for days, for a free and light solution to consume WP REST API with JWT (+ refresh) and I finally discovered this repo 🙏Unfortunately, the refresh endpoint isn't documented (because we can't PR the wiki pages). It's a shame because this is the killing feature I was looking for and I finally discovered it through PR history 😀

Related PR : https://github.com/jonathan-dejong/simple-jwt-authentication/pull/45
And forked documentation : https://github.com/qazsero/simple-jwt-authentication/wiki/Documentation

Could somebody update the wiki for futur users ? I think this could help a lot of peoples! 

Thanks again!
alex

**Comment by jonathan-dejong** [comment]
HI @alexbonhomme 
Thank you for the feedback and kind words!

I've updated the documentation now, you made it very easy for me by linking the PR and Docs from @qazsero :)

**Comment by qazsero** [comment]
I'm glad the PR was useful to you @alexbonhomme and thanks for pushing the request to add the docu to @jonathan-dejong, now I can finally close my fork
