### ISSUE TITLE
Name and Description for composer.json to allow for installation via composer

### ISSUE THREAD

**Issue by Gaffen** [jonathan-dejong/simple-jwt-authentication#6]
I was just attempting to install your plugin using composer but was presented with an `Undefined index: name` error, which I believe will prevent installation directly from git unless [both name and description are defined](https://packagist.org/)

**Comment by jonathan-dejong** [comment]
Hi @Gaffen 

I've not thought about that at all after taking over the project :) 
I've added a name and description now so try it out.. I've not published it to packagist tho.

**Comment by Gaffen** [comment]
Not to worry; if you need some help I could even try sending a couple of pull requests for you if they're welcome?

There were a couple of other features I was thinking of requesting (that I've implemented in my own deployment) too, but I'll need to collect them together as I'm doing some rapid prototyping right now.

**Comment by jonathan-dejong** [comment]
If they're well written and tested all PRs are very welcome! 
and of course if they would be useful to people in general using this plugin.
