### ISSUE TITLE
Token never expires

### ISSUE THREAD

**Issue by berlogi** [jonathan-dejong/simple-jwt-authentication#62]
Hello,

I've tried to simulate token expiration in my DB by changing issue, expire and last used times.
Even if I put the date 2 years ago, on token/validate request I'm getting 200 valide token.
After doing searches in the code, I've not found any line about expiration date check, so why you're talking about expiration error here?

**Expired Token**
`[
  {
    "code": "jwt_auth_invalid_token",
    "message": "Expired token",
    "data": {
      "status": 403
    }
  }
]`

Can you help me please?

**Comment by jonathan-dejong** [comment]
Hi @berlogi 

Actually the expiration part is checked by the php-jwt library this plugin uses. 
```php
// Check if this token has expired.
if (isset($payload->exp) && (time() - self::$leeway) >= $payload->exp) {
		throw new ExpiredException('Expired token');
}
```

Found in `includes/vendor/firebase/php-jwt/src/JWT.php`. 
So when creating a new access token we set the exp value (default is a week) and then the library checks against that. Relevant code in the plugin:

```php
$expire     = apply_filters( 'jwt_auth_expire', $issued_at + ( DAY_IN_SECONDS * 7 ), $issued_at, $user );
$uuid       = wp_generate_uuid4();

$token = array(
	'uuid' => $uuid,
	'iss'  => get_bloginfo( 'url' ),
	'iat'  => $issued_at,
	'nbf'  => $not_before,
	'exp'  => $expire,
	'data' => array(
		'user' => array(
			'id' => $user->data->ID,
		),
	),
);

```

**Comment by berlogi** [comment]
@jonathan-dejong thank you for your answer. But why when I’m changing expiration day in MySQL, I’m never getting expired token error?
